# Generated by Django 4.2 on 2024-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="заголовок"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=120, unique=True, verbose_name="слаг"),
                ),
                ("content", models.TextField(verbose_name="содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blogs/images",
                        verbose_name="превью(изображение)",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="дата публикации"),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=False, verbose_name="признак публикации"
                    ),
                ),
                (
                    "count_views",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "db_table": "blogs",
                "ordering": ("count_views",),
            },
        ),
    ]
