# Generated by Django 4.2 on 2024-07-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="blog",
            table="blog",
        ),
    ]
