# Generated by Django 4.2 on 2024-07-05 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                ("fio", models.CharField(max_length=150, verbose_name="ФИО")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "client",
                "ordering": ("email", "owner_client"),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Daily", "Ежедневно"),
                            ("Weekly", "Еженедельно"),
                            ("Monthly", "Ежемесячно"),
                        ],
                        max_length=15,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Завершена"),
                            ("Created", "Создана"),
                            ("Launched", "Запущена"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Актуальность рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "mailings",
                "ordering": ("datetime", "status"),
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=120, verbose_name="Статус рассылки"),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчет о рассылке",
                "verbose_name_plural": "Отчеты о рассылках",
                "db_table": "MailingAttempt",
                "ordering": ("status", "answer", "owner_mailing"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=120, verbose_name="Тема письма"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "message",
                "ordering": ("subject", "owner_message"),
            },
        ),
    ]
