# Generated by Django 4.2 on 2024-07-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailings",
            options={
                "ordering": ("datetime", "status"),
                "verbose_name": "Рассылку",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
