# Generated by Django 4.2 on 2024-07-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailings",
            options={
                "ordering": ("datetime", "status"),
                "permissions": [
                    ("View_any_mailing_lists", "Просматривать любые рассылки"),
                    ("Disable_mailing_lists", "Отключать рассылки"),
                ],
                "verbose_name": "Рассылку",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
