# Generated by Django 4.2 on 2024-07-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailings", "0003_alter_mailing_owner_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="owner_mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рассылки",
            ),
        ),
    ]
