# Generated by Django 4.2 on 2024-07-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("email", "owner_client"),
                "verbose_name": "Клиента",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
