# Generated by Django 4.2 on 2024-07-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Ежедневно", "Ежедневно"),
                    ("Еженедельно", "Еженедельно"),
                    ("Ежемесячно", "Ежемесячно"),
                ],
                max_length=15,
                verbose_name="Периодичность рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Завершена", "Завершена"),
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
