# Generated by Django 4.2 on 2024-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Succses", "Успешно"), ("Fail", "Неуспешно")],
                max_length=120,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
