# Generated by Django 4.2 on 2024-07-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0012_alter_mailingattempt_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ("start_mailing", "status"),
                "permissions": [
                    ("View_any_mailing_lists", "Просматривать любые рассылки"),
                    ("Disable_mailing_lists", "Отключать рассылки"),
                ],
                "verbose_name": "Рассылку",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="datetime",
            new_name="start_mailing",
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="datetime",
            new_name="data_mailing",
        ),
    ]
