# Generated by Django 4.2 on 2024-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0014_alter_mailingattempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Success", "Успешно"), ("Fail", "Неуспешно")],
                max_length=120,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
