# Generated by Django 4.2 on 2024-07-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0015_alter_mailingattempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_mailing",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
