# Generated by Django 4.2 on 2024-07-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0016_alter_mailing_start_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_mailing",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
