# Generated by Django 4.2 on 2024-07-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0018_alter_mailing_start_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(max_length=120, verbose_name="Статус рассылки"),
        ),
    ]
