# Generated by Django 4.2 on 2024-07-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0020_alter_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Завершена"),
                    ("Created", "Создана"),
                    ("Launched", "Запущена"),
                ],
                default="Created",
                max_length=10,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
