# Generated by Django 4.2 on 2024-07-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0022_alter_mailing_message"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mailingattempt",
            table="mailingattempt",
        ),
    ]
