# Generated by Django 4.2 on 2024-07-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0023_alter_mailingattempt_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ("status", "answer", "owner"),
                "verbose_name": "Отчет о рассылке",
                "verbose_name_plural": "Отчеты о рассылках",
            },
        ),
        migrations.RenameField(
            model_name="mailingattempt",
            old_name="owner_mailing",
            new_name="owner",
        ),
    ]
